function [mins,maxs] = dataMinMax(Analysis)
%MM_EXPMLGPWEI returns the minimum and maximum values of each parameter in
% all measured metrics
%
% ANALYSIS is the analytic data structure

[ActiveLinks_mins,ActiveLinks_maxs] = mm_ExpGamRayLN(Analysis.ActiveLinks_FitTool,Analysis.ActiveLinks_MLE,Analysis.ActiveLinks_Moments);
[InteractionTimes_mins,InteractionTimes_maxs] = mm_ExpMLGPWei(Analysis.InteractionTimes_FitTool,Analysis.InteractionTimes_MLE,Analysis.InteractionTimes_Moments);
[ActivityPotential_mins,ActivityPotential_maxs] = mm_ExpGamRayLN(Analysis.ActivityPotential_FitTool,Analysis.ActivityPotential_MLE,Analysis.ActivityPotential_Moments);
[NoContactTimes_mins,NoContactTimes_maxs] = mm_ExpGamRayLN(Analysis.NoContactTimes_FitTool,Analysis.NoContactTimes_MLE,Analysis.NoContactTimes_Moments);
[NodesActive_mins,NodesActive_maxs] = mm_ExpGamRayLN(Analysis.NodesActive_FitTool,Analysis.NodesActive_MLE,Analysis.NodesActive_Moments);
[Components_mins,Components_maxs] = mm_ExpGamRayLN(Analysis.Components_FitTool,Analysis.Components_MLE,Analysis.Components_Moments);
[Clustering_mins,Clustering_maxs] = mm_ExpGamRayLN(Analysis.Clustering_FitTool,Analysis.Clustering_MLE,Analysis.Clustering_Moments);
[ComponentNodes_mins,ComponentNodes_maxs] = mm_ExpGamRayLN(Analysis.ComponentNodes_FitTool,Analysis.ComponentNodes_MLE,Analysis.ComponentNodes_Moments);
[ComponentEdges_mins,ComponentEdges_maxs] = mm_ExpGamRayLN(Analysis.ComponentEdges_FitTool,Analysis.ComponentEdges_MLE,Analysis.ComponentEdges_Moments);


mins =        struct('ActiveLinks',ActiveLinks_mins,...
                    'InteractionTimes',InteractionTimes_mins,...
                    'ActivityPotential',ActivityPotential_mins,...
                    'NoContactTimes',NoContactTimes_mins,...
                    'NodesActive',NodesActive_mins,...
                    'Components',Components_mins,...
                    'Clustering',Clustering_mins,...
                    'ComponentNodes',ComponentNodes_mins,...
                    'ComponentEdges',ComponentEdges_mins...
                    );  
                
maxs =        struct('ActiveLinks',ActiveLinks_maxs,...
                    'InteractionTimes',InteractionTimes_maxs,...
                    'ActivityPotential',ActivityPotential_maxs,...
                    'NoContactTimes',NoContactTimes_maxs,...
                    'NodesActive',NodesActive_maxs,...
                    'Components',Components_maxs,...
                    'Clustering',Clustering_maxs,...
                    'ComponentNodes',ComponentNodes_maxs,...
                    'ComponentEdges',ComponentEdges_maxs...
                    );