function [] = la2latex(FitTool,MLE,Moments,num_people,dir_ref,name,opstat)
%LA2LATEX outputs data as a latex matrix
%
% FITTOOL is the fit tool data structure
% MLE is the most likelihood estimators data structure
% MOMENTS is the method of moments data structure
% NUM_PEOPLE is the number of people in the network
% DIR_REF is the save directory
% NAME is the property name
% OPSTAT is a flag that determines the format of the given data structure

cleanName = strrep(name, '.', '');
cleanName = strrep(cleanName, ' ', '_');

filename = ['LaTexTables_Local_',cleanName,'.txt'];
filepath = [dir_ref,'/',filename];
datasource = dir_ref(24:end-3);

if opstat == 1 %ExpGamRayLN
    
    lines = 53;
    tobuild = cell(lines,1);
    
    tobuild{001} = ['%Data From: ',datasource];
    tobuild{002} = ['\subsection{Results: ',datasource,' [',num2str(num_people),' Students]}'];
    tobuild{003} = '\begin{tabular}{|c|c|c||c|c||c|c||c|c||c|c|} \hline';
    tobuild{004} = ['\multicolumn{3}{|c||}{',name,'} & \multicolumn{2}{c||}{\textbf{Exponential}} & \multicolumn{2}{c||}{\textbf{Gamma}} & \multicolumn{2}{c||}{\textbf{Rayleigh}} & \multicolumn{2}{c|}{\textbf{Log-Normal}} \\ \hline'];
    tobuild{005} = ['\parbox[t]{2mm}{\multirow{16}{*}{\rotatebox[origin=c]{90}{Method of Moments}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(Moments.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(Moments.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(Moments.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(Moments.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
    tobuild{006} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(Moments.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(Moments.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
    tobuild{007} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
    tobuild{008} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
    tobuild{009} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.Statistics.Kuiper),'$} \\ \cline{3-11}'];
    tobuild{010} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.Statistics.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.Statistics.Watson),'$} \\ \cline{3-11}'];
    tobuild{011} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.Statistics.Anderson_Darling),'$} \\ \cline{3-11}'];
    tobuild{012} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.Statistics.Kullback_Leibler),'$} \\ \cline{3-11}'];
    tobuild{013} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.Statistics.Jensen_Shannon),'$} \\ \cline{2-11}'];
    tobuild{014} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
    tobuild{015} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
    tobuild{016} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.pValues.Kuiper),'$} \\ \cline{3-11}'];
    tobuild{017} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.pValues.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.pValues.Watson),'$} \\ \cline{3-11}'];
    tobuild{018} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.pValues.Anderson_Darling),'$} \\ \cline{3-11}'];
    tobuild{019} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.pValues.Kullback_Leibler),'$} \\ \cline{3-11}'];
    tobuild{020} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Gamma.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Rayleigh.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c|}{$',num2matlabstr(Moments.LogNormal.pValues.Jensen_Shannon),'$} \\ \hline \hline'];
    tobuild{021} = ['\parbox[t]{2mm}{\multirow{16}{*}{\rotatebox[origin=c]{90}{Curve Fitting Tool}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(FitTool.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(FitTool.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(FitTool.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(FitTool.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
    tobuild{022} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(FitTool.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(FitTool.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
    tobuild{023} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
    tobuild{024} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
    tobuild{025} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.Statistics.Kuiper),'$} \\ \cline{3-11}'];
    tobuild{026} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.Statistics.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.Statistics.Watson),'$} \\ \cline{3-11}'];
    tobuild{027} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.Statistics.Anderson_Darling),'$} \\ \cline{3-11}'];
    tobuild{028} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.Statistics.Kullback_Leibler),'$} \\ \cline{3-11}'];
    tobuild{029} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.Statistics.Jensen_Shannon),'$} \\ \cline{2-11}'];
    tobuild{030} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
    tobuild{031} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
    tobuild{032} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.pValues.Kuiper),'$} \\ \cline{3-11}'];
    tobuild{033} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.pValues.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.pValues.Watson),'$} \\ \cline{3-11}'];
    tobuild{034} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.pValues.Anderson_Darling),'$} \\ \cline{3-11}'];
    tobuild{035} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.pValues.Kullback_Leibler),'$} \\ \cline{3-11}'];
    tobuild{036} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Gamma.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Rayleigh.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c|}{$',num2matlabstr(FitTool.LogNormal.pValues.Jensen_Shannon),'$} \\ \hline \hline'];
    tobuild{037} = ['\parbox[t]{2mm}{\multirow{16}{*}{\rotatebox[origin=c]{90}{Maximum Likelihood Estimators}}} & \multicolumn{2}{|c||}{\multirow{2}{*}{\textbf{Parameters}}} & \multirow{2}{*}{Rate} & \multirow{2}{*}{$',num2matlabstr(MLE.Exponential.Parameters.Scale),'$} & Shape & $',num2matlabstr(MLE.Gamma.Parameters.Shape),'$ & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(MLE.Rayleigh.Parameters.Scale),'$} & Loc. & $',num2matlabstr(MLE.LogNormal.Parameters.Location),'$ \\ \cline{6-7}\cline{10-11}'];
    tobuild{038} = ['& \multicolumn{2}{|c||}{} & & & Scale & $',num2matlabstr(MLE.Gamma.Parameters.Scale),'$ & & & Scale & $',num2matlabstr(MLE.LogNormal.Parameters.Scale),'$ \\ \cline{2-11}'];
    tobuild{039} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
    tobuild{040} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
    tobuild{041} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.Statistics.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.Statistics.Kuiper),'$} \\ \cline{3-11}'];
    tobuild{042} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.Statistics.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.Statistics.Watson),'$} \\ \cline{3-11}'];
    tobuild{043} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.Statistics.Anderson_Darling),'$} \\ \cline{3-11}'];
    tobuild{044} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.Statistics.Kullback_Leibler),'$} \\ \cline{3-11}'];
    tobuild{045} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.Statistics.Jensen_Shannon),'$} \\ \cline{2-11}'];
    tobuild{046} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
    tobuild{047} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
    tobuild{048} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.pValues.Kuiper),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.pValues.Kuiper),'$} \\ \cline{3-11}'];
    tobuild{049} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.pValues.Watson),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.pValues.Watson),'$} \\ \cline{3-11}'];
    tobuild{050} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.pValues.Anderson_Darling),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.pValues.Anderson_Darling),'$} \\ \cline{3-11}'];
    tobuild{051} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.pValues.Kullback_Leibler),'$} \\ \cline{3-11}'];
    tobuild{052} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Gamma.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Rayleigh.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c|}{$',num2matlabstr(MLE.LogNormal.pValues.Jensen_Shannon),'$} \\ \hline \hline'];
    tobuild{053} = '\end{tabular}';
elseif opstat == 2 %ExpMLGPWei
        
    lines = 56;
    tobuild = cell(lines,1);
    
    tobuild{001} = ['%Data From: ',datasource];
    tobuild{002} = ['\subsection{Results: ',datasource,' [',num2str(num_people),' Students]}'];
    tobuild{003} = '\begin{tabular}{|c|c|c||c|c||c|c||c|c||c|c|} \hline';
    tobuild{004} = ['\multicolumn{3}{|c||}{',name,'} & \multicolumn{2}{c||}{\textbf{Exponential}} & \multicolumn{2}{c||}{\textbf{Mittag-Leffler}} & \multicolumn{2}{c||}{\textbf{Gen. Pareto}} & \multicolumn{2}{c|}{\textbf{Weibull}} \\ \hline'];
    tobuild{005} = ['\parbox[t]{2mm}{\multirow{19}{*}{\rotatebox[origin=c]{90}{Method of Moments}}} & \multicolumn{2}{|c||}{\multirow{3}{*}{\textbf{Parameters}}} & \multirow{3}{*}{Rate} & \multirow{3}{*}{$',num2matlabstr(Moments.Exponential.Parameters.Scale),'$} & Stability & $X$ & Shape & $',num2matlabstr(Moments.GenPareto.Parameters.Shape),'$ & Scale & $X$ \\ \cline{6-11}'];
    tobuild{006} = ['& \multicolumn{2}{|c||}{} & & & \multirow{2}{*}{Scale} & \multirow{2}{*}{$X$} & Scale & $',num2matlabstr(Moments.GenPareto.Parameters.Scale),'$ & \multirow{2}{*}{Shape} & \multirow{2}{*}{$X$} \\ \cline{8-9}'];
    tobuild{007} = ['& \multicolumn{2}{|c||}{} & & & & & Loc. & $',num2matlabstr(Moments.GenPareto.Parameters.Location),'$ & & \\ \cline{2-11}'];
    tobuild{008} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{009} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{010} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{011} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.Statistics.Watson),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{012} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{013} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{014} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{2-11}'];
    tobuild{015} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{016} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{017} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{018} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.pValues.Watson),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{019} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{020} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$X$} \\ \cline{3-11}'];
    tobuild{021} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(Moments.Exponential.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(Moments.GenPareto.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$X$} \\ \hline \hline'];
    tobuild{022} = ['\parbox[t]{2mm}{\multirow{19}{*}{\rotatebox[origin=c]{90}{Curve Fitting Tool}}} & \multicolumn{2}{|c||}{\multirow{3}{*}{\textbf{Parameters}}} & \multirow{3}{*}{Rate} & \multirow{3}{*}{$',num2matlabstr(FitTool.Exponential.Parameters.Scale),'$} & Stability & $',num2matlabstr(FitTool.MittagLeffler.Parameters.Stability),'$ & Shape & $',num2matlabstr(FitTool.GenPareto.Parameters.Shape),'$ & Scale & $',num2matlabstr(FitTool.Weibull.Parameters.Scale),'$ \\ \cline{6-11}'];
    tobuild{023} = ['& \multicolumn{2}{|c||}{} & & & \multirow{2}{*}{Scale} & \multirow{2}{*}{$',num2matlabstr(FitTool.MittagLeffler.Parameters.Scale),'$} & Scale & $',num2matlabstr(FitTool.GenPareto.Parameters.Scale),'$ & \multirow{2}{*}{Shape} & \multirow{2}{*}{$',num2matlabstr(FitTool.Weibull.Parameters.Shape),'$} \\ \cline{8-9}'];
    tobuild{024} = ['& \multicolumn{2}{|c||}{} & & & & & Loc. & $',num2matlabstr(FitTool.GenPareto.Parameters.Location),'$ & & \\ \cline{2-11}'];
    tobuild{025} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
    tobuild{026} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
    tobuild{027} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.Statistics.Kuiper),'$} \\ \cline{3-11}'];
    tobuild{028} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.Statistics.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.Statistics.Watson),'$} \\ \cline{3-11}'];
    tobuild{029} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.Statistics.Anderson_Darling),'$} \\ \cline{3-11}'];
    tobuild{030} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.Statistics.Kullback_Leibler),'$} \\ \cline{3-11}'];
    tobuild{031} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.Statistics.Jensen_Shannon),'$} \\ \cline{2-11}'];
    tobuild{032} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
    tobuild{033} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
    tobuild{034} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.pValues.Kuiper),'$} \\ \cline{3-11}'];
    tobuild{035} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.pValues.Watson),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.pValues.Watson),'$} \\ \cline{3-11}'];
    tobuild{036} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.pValues.Anderson_Darling),'$} \\ \cline{3-11}'];
    tobuild{037} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.pValues.Kullback_Leibler),'$} \\ \cline{3-11}'];
    tobuild{038} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Exponential.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.MittagLeffler.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.GenPareto.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$',num2matlabstr(FitTool.Weibull.pValues.Jensen_Shannon),'$} \\ \hline \hline'];
    tobuild{039} = ['\parbox[t]{2mm}{\multirow{19}{*}{\rotatebox[origin=c]{90}{Maximum Likelihood Estimators}}} & \multicolumn{2}{|c||}{\multirow{3}{*}{\textbf{Parameters}}} & \multirow{3}{*}{Rate} & \multirow{3}{*}{$',num2matlabstr(MLE.Exponential.Parameters.Scale),'$} & Stability & $X$ & Shape & $X$ & Scale & $',num2matlabstr(MLE.Weibull.Parameters.Scale),'$ \\ \cline{6-11}'];
    tobuild{040} = ['& \multicolumn{2}{|c||}{} & & & \multirow{2}{*}{Scale} & \multirow{2}{*}{$X$} & Scale & $X$ & \multirow{2}{*}{Shape} & \multirow{2}{*}{$',num2matlabstr(MLE.Weibull.Parameters.Shape),'$} \\ \cline{8-9}'];
    tobuild{041} = ['& \multicolumn{2}{|c||}{} & & & & & Loc. & $X$ & & \\ \cline{2-11}'];
    tobuild{042} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{Statistics}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.Statistics.Kolmogorov_D),'$} \\ \cline{3-11}'];
    tobuild{043} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.Statistics.Cramer_von_Mises),'$} \\ \cline{3-11}'];
    tobuild{044} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Kuiper),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.Statistics.Kuiper),'$} \\ \cline{3-11}'];
    tobuild{045} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Watson),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.Statistics.Watson),'$} \\ \cline{3-11}'];
    tobuild{046} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Anderson_Darling),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.Statistics.Anderson_Darling),'$} \\ \cline{3-11}'];
    tobuild{047} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.Statistics.Kullback_Leibler),'$} \\ \cline{3-11}'];
    tobuild{048} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.Statistics.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.Statistics.Jensen_Shannon),'$} \\ \cline{2-11}'];
    tobuild{049} = ['& \parbox[t]{2mm}{\multirow{7}{*}{\rotatebox[origin=c]{90}{p-Values}}} & Kol D & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Kolmogorov_D),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.pValues.Kolmogorov_D),'$} \\ \cline{3-11}'];
    tobuild{050} = ['& & CvM & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Cramer_von_Mises),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.pValues.Cramer_von_Mises),'$} \\ \cline{3-11}'];
    tobuild{051} = ['& & Kuiper & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Kuiper),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.pValues.Kuiper),'$} \\ \cline{3-11}'];
    tobuild{052} = ['& & Watson & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Watson),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.pValues.Watson),'$} \\ \cline{3-11}'];
    tobuild{053} = ['& & And-Dar & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Anderson_Darling),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.pValues.Anderson_Darling),'$} \\ \cline{3-11}'];
    tobuild{054} = ['& & Kul-Lei & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Kullback_Leibler),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.pValues.Kullback_Leibler),'$} \\ \cline{3-11}'];
    tobuild{055} = ['& & Jen-Sha & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Exponential.pValues.Jensen_Shannon),'$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$X$} & \multicolumn{2}{c||}{$',num2matlabstr(MLE.Weibull.pValues.Jensen_Shannon),'$} \\ \hline'];
    tobuild{056} = '\end{tabular}';

end

fileID = fopen(filepath,'w');
fprintf(fileID,'%s\r\n',tobuild{:});
fclose(fileID);
end

